### ISSUE TITLE
When I only turn on network event tracking, process creation / destruction events will still be captured

### ISSUE THREAD

**Issue by SiyerBOBO** [zodiacon/ProcMonXv2#5]
When I only turn on network event tracking, process creation / destruction events will still be captured.

`tm.SetKernelEventTypes({ KernelEventTypes::Network});`

![image](https://user-images.githubusercontent.com/47243555/152753013-b80f99a8-0498-4948-b35b-b460617daff1.png)

**Comment by SiyerBOBO** [comment]
Is this a bug? The code is based on the ProcMonC project.

**Comment by zodiacon** [comment]
Yes, process events are always captured. This is by design.

**Comment by SiyerBOBO** [comment]
Well, thank you. The work has brought me a lot of help. Thank you for your answer and your contribution to the community.
